WebApplication2/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2;

namespace WebApplication2.Controllers
{
    public class BrandController : Controller
    {
        private Database1Entities db = new Database1Entities();

        // GET: /Brand/
        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        // GET: /Brand/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: /Brand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Brand/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,Descript,Addrs")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: /Brand/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: /Brand/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Descript,Addrs")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: /Brand/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: /Brand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc4Application5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {            
            return View();
        }

        public ActionResult About()
        {            
            return View();
        }

      
    }
}

WebApplication2/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2;

namespace WebApplication2.Controllers
{
    public class ProductController : Controller
    {
        private Database1Entities db = new Database1Entities();

        // GET: /Product/
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Brand);
            return View(products.ToList());
        }

        // GET: /Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: /Product/Create
        public ActionResult Create()
        {
            ViewBag.Brand_Id = new SelectList(db.Brands, "Id", "Name");
            return View();
        }

        // POST: /Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,Price,Descript,Brand_Id")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Brand_Id = new SelectList(db.Brands, "Id", "Name", product.Brand_Id);
            return View(product);
        }

        // GET: /Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Brand_Id = new SelectList(db.Brands, "Id", "Name", product.Brand_Id);
            return View(product);
        }

        // POST: /Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Price,Descript,Brand_Id")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Brand_Id = new SelectList(db.Brands, "Id", "Name", product.Brand_Id);
            return View(product);
        }

        // GET: /Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/Views/Brand/Create.cshtml
@model WebApplication2.Brand

@{
    ViewBag.Title = "Add New Brand";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brand</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Descript">Description</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descript)
                @Html.ValidationMessageFor(model => model.Descript)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Descript">Address</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Addrs)
                @Html.ValidationMessageFor(model => model.Addrs)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebApplication2/Views/Brand/Delete.cshtml
@model WebApplication2.Brand

@{
    ViewBag.Title = "Delete brand";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label class="control-label col-md-2" for="Descript">Name</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            <label class="control-label col-md-2" for="Descript">Description</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descript)
        </dd>

        <dt>
           <label class="control-label col-md-2" for="Descript">Address</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addrs)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication2/Views/Brand/Details.cshtml
@model WebApplication2.Brand

@{
    ViewBag.Title = "Details of brand";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Brand</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            <label class="control-label col-md-2" for="Descript">Name</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            <label class="control-label col-md-2" for="Descript">Description</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descript)
        </dd>

        <dt>
            <label class="control-label col-md-2" for="Descript">Address</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addrs)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication2/Views/Brand/Edit.cshtml
@model WebApplication2.Brand

@{
    ViewBag.Title = "Edit brand";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brand</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
           <label class="control-label col-md-2" for="Descript">Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
           <label class="control-label col-md-2" for="Descript">Description</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descript)
                @Html.ValidationMessageFor(model => model.Descript)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Descript">Address</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Addrs)
                @Html.ValidationMessageFor(model => model.Addrs)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebApplication2/Views/Brand/Index.cshtml
@model IEnumerable<WebApplication2.Brand>

@{
    ViewBag.Title = "List of brands";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            <label class="control-label col-md-2" for="Descript">Description</label>
        </th>
        <th>
            <label class="control-label col-md-2" for="Descript">Address</label>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descript)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Addrs)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebApplication2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}



<article>
    <div class="row">
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      
      <div class="caption">
        <h3>Sample </h3>
        <p> Use this area to provide additional information. Use this area to provide additional information.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
 
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       
      <div class="caption">
        <h3>Sample</h3>
        <p> Use this area to provide additional information. Use this area to provide additional information.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
 
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p> Use this area to provide additional information. Use this area to provide additional information.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
          <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p> Use this area to provide additional information. Use this area to provide additional information.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
          <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p> Use this area to provide additional information. Use this area to provide additional information.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
          <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p> Use this area to provide additional information. Use this area to provide additional information.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
          <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p> Use this area to provide additional information. Use this area to provide additional information.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
          <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p> Use this area to provide additional information. Use this area to provide additional information.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>
</article>

 

WebApplication2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <div class="jumbotron">
        <h1>Welcome to Makeup Collection!</h1>
        <p>
            Welcome to Makeup Collection it support crud operation for Brands and Products
        </p>
         
    </div>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>About application</h5>
        this application store and display data from brands and products. it is a basic model for a shpping website
    </li>

    
</ol>

WebApplication2/Views/Product/Create.cshtml
@model WebApplication2.Product

 @{
    ViewBag.Title = "Add product";
 
}
 
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Product</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price)
                    @Html.ValidationMessageFor(model => model.Price)
                </div>
            </div>
    
            <div class="form-group">
           <label class="control-label col-md-2" for="Descript">Description</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descript)
                    @Html.ValidationMessageFor(model => model.Descript)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Brand_Id, "Brand_Id", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Brand_Id", String.Empty)
                    @Html.ValidationMessageFor(model => model.Brand_Id)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
 

WebApplication2/Views/Product/Delete.cshtml
@model WebApplication2.Product

 @{
    ViewBag.Title = "Delete products";
 
}
 
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Product</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
    
            <dt>
              <label class="control-label col-md-2" for="Descript">Description</label>
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Descript)
            </dd>
    
            <dt>
                <label class="control-label col-md-2" for="Descript">Brand Name</label>
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Brand.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
 

WebApplication2/Views/Product/Details.cshtml
@model WebApplication2.Product
@{
    ViewBag.Title = "View detail of products";
 
}
 
<body>
    <div>
        <h4>Product</h4>
    	<hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
    
            <dt>
                <label class="control-label col-md-2" for="Descript">Description</label>
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Descript)
            </dd>
    
            <dt>
                <label class="control-label col-md-2" for="Descript">Brand Name</label>
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Brand.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
 

WebApplication2/Views/Product/Edit.cshtml
@model WebApplication2.Product

 @{
    ViewBag.Title = "Edit products";
 
}
 
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Product</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price)
                    @Html.ValidationMessageFor(model => model.Price)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Descript, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descript)
                    @Html.ValidationMessageFor(model => model.Descript)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Brand_Id, "Brand_Id", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Brand_Id", String.Empty)
                    @Html.ValidationMessageFor(model => model.Brand_Id)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
 

WebApplication2/Views/Product/Index.cshtml
@model IEnumerable<WebApplication2.Product>
 
@{
    ViewBag.Title = "List of products";
 
}

 
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    @foreach (var item in Model)
    {
        
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail">

                <div class="caption">
                    <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
                    <a href="#" class="btn btn-default" role="button">@Html.DisplayFor(modelItem => item.Brand.Name)</a>
                    <p>@Html.DisplayFor(modelItem => item.Descript).</p>
                    <p><a href="#" class="btn btn-primary" role="button">$ @Html.DisplayFor(modelItem => item.Price)</a></p>

                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </div>
            </div>
        </div>
         
               
           
    }

 

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title  -  Makeup Collection</title>
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/styles.css" rel="stylesheet" />
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
   @*    // @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    </head>
    <body>
        <header>

            <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Makeup Collection</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Makeup Collection</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">   
          <li>@Html.ActionLink("Home", "Index", "Home")</li>
           <li>@Html.ActionLink("About", "About", "Home")</li>
       
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>@Html.ActionLink("Add", "Create", "Brand")</li>
            <li>@Html.ActionLink("View", "Index", "Brand")</li>
             
          </ul>
        </li> 
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Product <span class="caret"></span></a>
          <ul class="dropdown-menu">
         <li>@Html.ActionLink("Add", "Create", "Product")</li>
            <li>@Html.ActionLink("View", "Index", "Product")</li>
          
          </ul>
        </li>
      </ul>      
     
    </div> 
  </div> 
</nav>
             
        </header>
        <div class="container body">
            <div class="row">
            @RenderSection("featured", required: false)

            </div>
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Shreya 200375832 Interactive media design web, code: comp2084</p>
                </div>
            </div>
        </footer>

      @*  @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)*@
    </body>
</html>